#服务的名称
spring:
  application:
    name: product-service
server:
  port: 8771

#指定注册中心地址
eureka:
  client:
    # 定时刷新本地缓存时间
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  # 心跳间隔，5秒
  instance:
    leaseRenewalIntervalInSeconds: 5
    # 没有心跳的淘汰时间，5秒
    leaseExpirationDurationInSeconds: 5

# ribbon缓存时间
ribbon:
  ServerListRefreshInterval: 2000


